spring:
  redis:
    redisson:
      file: classpath:redisson-single-dev.yml

bytedance:
  open:
    componentAppId: "your componentAppId"
    componentSecret: "your componentSecret"
    componentToken: "your componentToken"
    componentAesKey: "your componentAesKey"
    serverDomain:
      request:
        - "your.server.domain"
